.PHONY: gen-demo-proto
gen-demo-proto:
	@cd demo/demo_proto && cwgo server -I ../../idl --type RPC --module biz-demo/gomall/demo/demo_proto --service demo_proto --idl ../../idl/echo.proto

.PHONY: gen-demo-thrift
gen-demo-thrift:
	@cd demo/demo-thrift && cwgo server -I ../../idl --type RPC --module biz-demo/gomall/demo/demo_thrift --service demo_thrift --idl ../../idl/echo.thrift

.PHONY: gen-frontend
gen-frontend:
	@cd app/frontend && cwgo server --type HTTP --idl  ../../idl/frontend/product_page.proto --service frontend -module biz-demo/gomall/app/frontend -I ../../idl -I /home/qiang-ubun/pan1/download/ProtoBuf/protoc-29.0-rc-2-linux-x86_64/include

.PHONY: gen-user
gen-user:
	@cd rpc_gen && cwgo client --type RPC --service user --module biz-demo/gomall/rpc_gen  -I ../idl  --idl ../idl/user.proto
	@cd app/user && cwgo server --type RPC --service user --module biz-demo/gomall/app/user --pass "-use biz-demo/gomall/rpc_gen/kitex_gen"  -I ../../idl  --idl ../../idl/user.proto

.PHONY: gen-product
gen-product:
	@cd rpc_gen && cwgo client --type RPC --service product --module biz-demo/gomall/rpc_gen  -I ../idl  --idl ../idl/product.proto
	@cd app/product && cwgo server --type RPC --service product --module biz-demo/gomall/app/product --pass "-use biz-demo/gomall/rpc_gen/kitex_gen"  -I ../../idl  --idl ../../idl/product.proto

